### ISSUE TITLE
Exam task for Natalia Petukhova

### ISSUE THREAD

**Issue by YakutovDmitriy** [NataliaPetukhova/Python-course#14]
#### Main requirements

Your program should never fail.

You are free to implement the task as you want. In particular, if there are some uncertainties, you have to decide what to do.

You are free to add some functionality. Please describe all features you added.

#### Implement application `market.py` to work with online market.

You should store information about products in file [goods.mt](https://gist.github.com/YakutovDmitriy/96a891618b27b851ba504fd54e89415e).

Each good have several properties:
  * Name
  * Category
  * Price (in dollars)
  * Rating (out of 10 points)

---

* Add: `python market.py add <Name> <Category> <Price> <Rating>`

    Command should add new product to market. If there exists an item with the same name, print a message about it.

* Remove: `python market.py remove <Name>`

    Command should remove a product from market. If there is no product with such name, print a message.

* Best: `python market.py best <Category>`

    Command should print full info (name, category, price and rating) about the best product (with highest rating) from category `<Category>`. If there are several such products, print the cheapest one. If there are no products from this category, print a message about it.

* Recommend: `python market.py recommend <Price> <Category>`

    Command should print the best product from category `<Category>` such that its price is not higher than `<Price>`. If there is no such product, print a message about it.

**Comment by NataliaPetukhova** [comment]
Exam folder is added

**Comment by YakutovDmitriy** [comment]
Hello!

* It is very good that you used classes for implementation!
* `get_all_items`. Lets take a look and the following product:
    ```
    Name: Computer-Game-Name-Quiz
    Category: Toy-Name-Quiz
    Price: $6
    Rating: 6
    ```
    You will parse this item in incorrect way: second line (category) will be parsed as name because this line contains substring `'Name'`. It could be better to use something like `line.startswith("Name")`
* `best` and `recommend`. There are some problems with rating: you doesn't count with rating in both functions: `best` prints the cheapest product and `recommend` prints the most expencive product over all products that are cheaper than `price`
* Your program fails if you put incorrect data in arguments, e.g. `python market.py recomment foo`

You got 6 points over 10 for exam

**Comment by YakutovDmitriy** [comment]
I thought a bit more and decided that it is 7, not 6

**Comment by NataliaPetukhova** [comment]
Thanks :)
